sonar.projectKey=NicoleBono_os-service
sonar.organization=nicolebono
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,test/bdd/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*.spec.ts,**/*.module.ts,src/main.ts,src/tracing.ts
